spring:
  datasource:
    # DB 접속 주소
    # url: jdbc:mysql://{ec2 public IP}:3306/{DB 이름}
    url: jdbc:mariadb://heyhey.i234.me:3307/dubu?useSSL=false&allowPublicKeyRetrieval=true
    # DB 접속 계정
    username: user
    password: Qwer1234!@
    # DB 드라이버
    driver-class-name: org.mariadb.jdbc.Driver
  jpa: # JPA 설정
    database-platform: org.hibernate.dialect.MariaDBDialect # DB 방언
    show-sql: true # SQL 쿼리 출력 여부
    hibernate: # 하이버네이트 설정
      ddl-auto:  update  # 스키마 자동 생성 (create, create-drop, update, validate)
      format_sql: true  # SQL pretty print

server: # 서버 설정
  port : 3333 # 서버 포트